### ISSUE TITLE
[meta] I'm really curious about how this website works!

### ISSUE THREAD

**Issue by behdad** [commontype-standard/commontype-standard.github.io#10]
Care to explain? The XSLT, HarfBuzz, Hypothes.is, how did you pull this off?! It's insane! Of course you did, you're Simon!

**Comment by simoncozens** [comment]
Most of the XSLT (and Harfbuzz thing, which we are not using) was inherited from upstream: https://github.com/adobe-type-tools/aots
Adding hypothes.is commenting is literally two lines of code in the Jekyll config:
```
head_scripts:
    - https://cdn.hypothes.is/hypothesis
```

**Comment by simoncozens** [comment]
Automated GH pages build with github actions merging and re-committing to the tree was a headache though. :-)

**Comment by behdad** [comment]
Thanks.
